require("__cargo-ships__/prototypes/water_rails")
require("__cargo-ships__/prototypes/buoys")
require("__cargo-ships__/prototypes/ships")
require("__cargo-ships__/prototypes/ship_pump")
require("__cargo-ships__/prototypes/oil_rig")
require("__cargo-ships__/prototypes/bridge_gate")
require("__cargo-ships__/prototypes/electric_pole")
--require("__cargo-ships__/prototypes/crane")
